[package]
name = "mdbook-mermaid"
version = "0.2.2-alpha.0"
authors = ["Jan-Erik Rediger <janerik@fnordig.de>"]
description = "mdbook preprocessor to add mermaid support"
license = "MPL-2.0"
homepage = "https://github.com/badboy/mdbook-mermaid"
repository = "https://github.com/badboy/mdbook-mermaid"

[dependencies]
mdbook = "0.3"
pulldown-cmark = "0.5"
pulldown-cmark-to-cmark = "1.2"
env_logger = "0.6"
log = "0.4"
clap = "2.33"
serde_json = "1.0"
