[package]
name = "mdbook-mermaid"
version = "0.1.0"
authors = ["Jan-Erik Rediger <janerik@fnordig.de>"]

[dependencies]
mdbook = "0.3.0"
pulldown-cmark = "0.5"
pulldown-cmark-to-cmark = "1.2"
env_logger = "0.6"
log = "0.4"
clap = "2.33"
serde_json = "1.0"
