[package]
name = "mdbook-mermaid"
version = "0.2.5-alpha.0"
authors = ["Jan-Erik Rediger <janerik@fnordig.de>"]
description = "mdbook preprocessor to add mermaid support"
license = "MPL-2.0"
homepage = "https://github.com/badboy/mdbook-mermaid"
repository = "https://github.com/badboy/mdbook-mermaid"
edition = "2018"

[dependencies]
mdbook = "0.3"
pulldown-cmark = "0.6.1"
pulldown-cmark-to-cmark = "2.0.1"
env_logger = "0.7.1"
log = "0.4"
clap = "2.33"
serde_json = "1.0"
